### ISSUE TITLE
CMake Error: target name "test" is reserved or not valid for certain CMake features,

### ISSUE THREAD

**Issue by fanshi14** [awesomericky/complex-env-navigation#1]
Hi, 

Thanks for your contribution!

I am trying to play with the demo codes, however, I met CMake Error when trying:
`cd complex-env-navigation`
`python setup.py develop`

Output in cmd line is:

> CMake Error at /home/xxx/raisim_ws/raisimLibMaster/thirdParty/pybind11/tools/pybind11Tools.cmake:165 (add_library):
  The target name "test" is reserved or not valid for certain CMake features,
  such as generator expressions, and may result in undefined behavior.
Call Stack (most recent call first):
  CMakeLists.txt:79 (pybind11_add_module)
 CMake Error at CMakeLists.txt:85 (target_link_libraries):
  Cannot specify link libraries for target "test" which is not built by this
  project.
-- Configuring incomplete, errors occurred!
See also "/home/xxx/raisim_ws/raisimLibMaster/complex-env-navigation/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".

I could not figure out the problem. Could you give me some hints about this error?

OS: Ubuntu 18.04, python3.8, conda

**Comment by awesomericky** [comment]
Are you using CLion? I checked the repository running normally in the terminal by following the instructions in the README.md. 

I think there is a problem with the CLion configuration and should reload CMake project.

Remove `build`, `cmake-build-debug`, and `raisim_gym_torch.egg-info` located in `/home/xxx/raisim_ws/raisimLibMaster/complex-env-navigation` if exists. 

Then, run `cmake .. -DCMAKE_INSTALL_PREFIX=/home/awesomericky/raisim/raisim_build -DRAISIM_EXAMPLE=ON -DRAISIM_PY=ON -DPYTHON_EXECUTABLE=$(python3 -c "import sys; print(sys.executable)")`. 

Lastly, build the environment by running `python setup.py develop`.

**Comment by fanshi14** [comment]
Thank you! 
I changed to another desktop, it works well.
It seems that my previous desktop with RTX 3080 GPU had conflicts with some pytorch version.
